[package]
name = "loco-client"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3.14"
loco = { path = "../loco" }
tokio = "1.5.0"
tokio-native-tls = "0.3.0"
tokio-util = { version = "0.6.6", features = ["codec"] }
